Repository wecode-bootcamp-korea/49-1st-Team2-backend, pull requests merged in 2023-09, with the labels that each got.

#4 Feature/eunchae
  controllers/loginController.js
  db/migrations/20230911064620_create_user_table.sql
  services/loginService.js
Labels: bug

#2 Feature/hyunjin
  controllers/resetPasswordController.js
  package-lock.json
  package.json
  routes/userRouter.js
  services/resetPasswordServices.js
  utils/isValidData.js
  utils/throwError.js
Labels: 추가 기능 구현 중

#6 feat: 스레드 작성 - 스레드 작성 기능 추가
  controllers/threadController.js
  routes/index.js
  routes/threadRouter.js
  services/threadService.js
Labels: 완료

#7 refactor: 스레드 작성 - 필요없는 컬럼 제거
  db/migrations/20230911064804_create_threads_table.sql
  services/threadService.js
Labels: bug

#8 refactor: 공통 - controllers, services 일관화
  controllers/index.js
  controllers/loginController.js
  controllers/resetPasswordController.js
  controllers/signUpController.js
  controllers/threadController.js
  controllers/userController.js
  middlewares/index.js
  routes/threadRouter.js
  routes/userRouter.js
  services/index.js
  services/loginService.js
  services/resetPasswordServices.js
  services/signUpService.js
  services/threadService.js
  services/userService.js
  utils/index.js
  utils/isValidData.js
  utils/tokenGeneration.js
Labels: 완료

#11 비밀번호 찾기 기능 수정 및 controller service dao 수정
  controllers/index.js
  controllers/signUpController.js
  controllers/threadController.js
  controllers/userController.js
  models/index.js
  models/userDao.js
  routes/threadRouter.js
  routes/userRouter.js
  services/index.js
  services/threadService.js
  services/userService.js
Labels: 완료

#12 feat: 스레드 상세보기 - 개인스레드 가져오기 구현
  controllers/index.js
  controllers/threadController.js
  models/index.js
  models/threadDao.js
  routes/threadRouter.js
  services/index.js
  services/threadService.js
Labels: 완료

#13 fix: 스레드 상세보기 - 구현 오류로 삭제
  controllers/index.js
  controllers/threadController.js
  models/userDao.js
  routes/threadRouter.js
  services/index.js
  services/threadService.js
Labels: 수정 요청

#14 chore: dbmate dbmigration 설정 파일 nickname varchar 개수 제한 수정
  db/migrations/20230911064620_create_user_table.sql
Labels: 수정 요청

#15 fix: datasource 순환 종속성 문제 수정
  app.js
  models/dataSource.js
  models/threadDao.js
  models/userDao.js
Labels: 수정 요청

#17 feat: 스레드 펼쳐보기
  controllers/index.js
  controllers/threadController.js
  models/dataSource.js
  routes/threadRouter.js
  services/index.js
  services/threadService.js
Labels: 완료

#19 refactor: 스레드 작성 - Dao 와 Service 분리
  models/index.js
  models/threadDao.js
  services/threadService.js
Labels: 완료

#27 fix: 스레드 펼쳐보기 - 단일 스레드 불러오기 로직 수정
  controllers/threadController.js
  models/threadDao.js
Labels: 완료

#32 1.0 version release
  .eslintrc
  .gitignore
  .prettierrc
  app.js
  controllers/commentController.js
  controllers/index.js
  controllers/threadController.js
  controllers/userController.js
  db/migrations/20230911064620_create_user_table.sql
  db/migrations/20230911064804_create_threads_table.sql
  db/migrations/20230911065003_create_comments_table.sql
  db/migrations/20230911065108_create_threads_likes_table.sql
  middlewares/index.js
  models/commentDao.js
  models/dataSource.js
  models/index.js
  models/threadDao.js
  models/userDao.js
  package-lock.json
  package.json
  readme.md
  routes/commentRouter.js
  routes/index.js
  routes/threadRouter.js
  routes/userRouter.js
  services/commentService.js
  services/index.js
  services/threadService.js
  services/userService.js
  utils/index.js
Labels: 완료
